[project]
name = "acidentes-piracicaba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.20.0",
    "pandas>=2.3.3",
    "streamlit>=1.53.1",
    "streamlit-folium>=0.26.1",
]
